# Generated by Django 5.0.2 on 2024-03-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaint', '0002_moneydonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='moneydonation',
            name='donation_count',
            field=models.IntegerField(default=1),
        ),
    ]
