# Generated by Django 5.0.2 on 2024-03-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaint', '0003_donation_donation_count_moneydonation_donation_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ashram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('otp', models.CharField(max_length=6)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
