# Generated by Django 5.0.2 on 2024-03-27 08:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaint', '0004_ashram'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='imestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
