# Generated by Django 5.0.2 on 2024-03-27 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Complaint', '0005_donation_imestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='imestamp',
            new_name='timestamp',
        ),
    ]
