# Generated by Django 5.0.2 on 2024-03-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaint', '0007_functionhall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionhall',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
