# Generated by Django 5.0.2 on 2024-03-29 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Complaint', '0008_alter_functionhall_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FunctionHall',
        ),
    ]
