# Generated by Django 5.0.2 on 2024-04-02 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Complaint', '0011_functionhall_delete_complaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='quantity',
            new_name='Quantity',
        ),
    ]
