# Generated by Django 5.0.2 on 2024-04-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaint', '0013_volunteer_remove_ashram_otp_remove_functionhall_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('complaint_type', models.CharField(max_length=50)),
                ('complaint_text', models.TextField()),
                ('solved', models.BooleanField(default=False)),
            ],
        ),
    ]
