# Generated by Django 5.0.2 on 2024-05-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaint', '0014_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='complaint_type',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='solved',
        ),
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
